version: '3.6'  
services:  
  app:
    build:
      context: ./app
    depends_on:
      - mongo
    environment:
      - S_MONGO_URI=mongodb://mongo:27017
      - S_REQUEST_MAX_SIZE=1000000
      - S_DEBUG=True
      - S_AUTH_LOGIN_ENDPOINT=/user/login
      - S_USER_ENDPOINT=/user/
      - S_MONGO_DB_NAME=test
    ports:
      - "8000:8000"
    image: python
    volumes:
      - './app:/app'
  mongo:
    image: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
        - 27017:27017
    command: mongod --logpath=/dev/null # --quiet