version: '3.6'  
services:  
  app:
    build:
      context: .
    depends_on:
      - mongo
    ports:
      - "8000:8000"
  mongo:
    image: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
        - 27017:27017
    command: mongod --logpath=/dev/null # --quiet
volumes:  
  redis_data: